replicaCount: 1

image:
  repository: "docker.io"
  tag: "prodms/test-app"
  version: "1.0.0-SNAPSHOT"
  pullPolicy: IfNotPresent

app:
  id: "test-app-id"
  port: 8080

env:
  valuesFromSecretRef:
    - name: TEST_SECRET_1
      secretName: secret-name-1
      key: secret-key
    - name: TEST_SECRET_2
      secretName: secret-name
      key: secret-key-2
