name: Helm Publish

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Package Helm Chart
        run: |
          helm dependency update . # Обновить зависимости (если есть)
          helm package . #--version  ${{ github.ref_name }} # Упаковать Chart
          CHART_NAME=$(grep '^name:' ./Chart.yaml | awk '{print $2}')
          CHART_VERSION=$(grep '^version:' ./Chart.yaml | awk '{print $2}')

          echo "Chart Name: $CHART_NAME"
          echo "Chart Version: $CHART_VERSION"
          
          echo "CHART_FULL_NAME=$CHART_NAME-$CHART_VERSION.tgz" >> $GITHUB_ENV

      # Шаг 4: Логин в GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Шаг 5: Публикация Helm Chart в GHCR
      - name: Push Helm Chart to GHCR
        run: |
          echo $CHART_FULL_NAME
          helm push $CHART_FULL_NAME oci://ghcr.io/yuryklimchuk/prodms